"""Generate the QA rule set document from the store (deliverable D2).

The question requires the rule set to be documented **and** to report how many
points each rule removed or flagged. Both existed; the counts only existed as
console output at build time, so a reader of the repository could not see them
without running the pipeline. `qa_rules.md` appeared in the planned repository
layout and was never written.

Generated rather than hand-maintained, for the reason the Q3 constraint register
is: a rule table typed beside the code is wrong within a day. Every count here is
queried from the store this run produced, and every threshold cites the decision
that set it, so the document cannot claim a rule the pipeline does not apply or
a count the data does not support.

    python part1_q1/src/build_qa_rules_doc.py
"""

from __future__ import annotations

import sys
from pathlib import Path

import duckdb

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
import config  # noqa: E402
from stage02_qa import RULES  # noqa: E402

OUT = HERE.parent / "docs" / "qa_rules.md"

# Threshold and its source, keyed by rule prefix. The decision ids are the
# entries in DECISIONS.md; the question is explicit that arbitrary thresholds
# lose marks and defended ones do not.
SOURCES: dict[str, tuple[str, str]] = {
    "QA01": ("9-13 March 2026", "D-004a - the campaign window stated in the pack"),
    "QA02": ("07:00-16:59", "D-004b - measured from the activity plateau, not assumed"),
    "QA03": ("15 km/h reported", "D-004c - speed is bimodal; any cut from 6 to 120 km/h flags the same 1,437 points"),
    "QA04": ("15 km/h implied", "D-004c - the same threshold applied to position-derived speed"),
    "QA05": ("no exclusion", "D-004d - a fixed cut removes 62% of eight teams' tracks and manufactures a coverage finding from an equipment property"),
    "QA06": ("same team, same minute, different position", "D-002 - the collision is the thing in dispute, so it is flagged, never resolved silently"),
    "QA07": ("5 min interruption, 15 min outage", "D-004e - counts barely move across a 3x change, so the finding is insensitive to the cut"),
    "QA08": ("outside the operational envelope", "D-008 - null island excluded, transposition corrected only where corroborated within 500 m"),
    "QA09": ("5 minutes stationary", "D-004g - the same definition as a visit, so it marks the signal as much as a defect"),
}


def main() -> None:
    if not config.DB_PATH.exists():
        sys.exit(f"No store at {config.DB_PATH}. Run stage01 and stage02 first.")

    con = duckdb.connect(str(config.DB_PATH))
    con.execute("INSTALL spatial; LOAD spatial;")
    q = lambda sql: con.execute(sql).fetchone()[0]

    stored = q("SELECT count(*) FROM track_point")
    usable = q("SELECT count(*) FROM track_qa WHERE use_for_coverage")
    judged = q("SELECT count(*) FROM track_qa")

    rows = []
    for label, disposition, predicate in RULES:
        count = q(f"SELECT count(*) FROM track_qa WHERE {predicate}")
        prefix = label.split()[0][:4]
        threshold, source = SOURCES.get(prefix, ("-", "-"))
        rows.append((label, disposition, threshold, source, count))

    a = [].append
    lines: list[str] = []
    a = lines.append

    a("# Quality assurance rule set (D2)")
    a("")
    a("**Generated by `build_qa_rules_doc.py` from the store this run produced.**")
    a("Counts are queried, not transcribed. Rule definitions come from the same")
    a("`RULES` table `stage02_qa.py` applies, so this document cannot describe a")
    a("rule the pipeline does not run.")
    a("")
    a("**Rules flag; they do not delete.** Every point read is stored and every")
    a("stored point carries a quality decision. *Exclude* means excluded from")
    a("coverage attribution, not removed from the store - the pack asks for this")
    a("twice, and it is what makes a threshold reversible.")
    a("")
    a("| Rule | Disposition | Threshold | Points | Source of the threshold |")
    a("|---|---|---|---:|---|")
    for label, disposition, threshold, source, count in rows:
        a(f"| {label} | {disposition} | {threshold} | {count:,} | {source} |")
    a("")
    a("## Reconciliation")
    a("")
    a("| | |")
    a("|---|---:|")
    a(f"| Points in the store | {stored:,} |")
    a(f"| Points carrying a quality decision | {judged:,} |")
    a(f"| **Usable for coverage attribution** | **{usable:,}** ({100*usable/stored:.1f}%) |")
    a("")
    a("Counts sum to more than the store because a point can fail several rules -")
    a("a fix outside the campaign window is usually outside duty hours too. The")
    a("reconciliation that matters is the last line: **every stored point has a")
    a("quality decision**, asserted by `stage02_qa.py` and tested by")
    a("`tests/test_store.py`.")
    a("")
    a("## The five the question names")
    a("")
    a("| Required | Implemented as |")
    a("|---|---|")
    a("| Implausible speeds | QA03 and QA04 - the logger's claim and the position-derived value are different assertions, so they are separate rules |")
    a("| Positional accuracy thresholds | QA05 - addressed and **deliberately excludes nothing**; accuracy scales the attribution tolerance instead (D-005) |")
    a("| Points outside campaign duty hours | QA02 |")
    a("| Gaps in the fix sequence | QA07, at two severities |")
    a("| Stationary clusters | QA09 |")
    a("")
    a("QA01, QA06 and QA08 are additional: the campaign window, the colliding-key")
    a("conflict that 63% of the store carries, and coordinates that are")
    a("geographically impossible.")
    a("")

    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"\nQA rule set -> {OUT.relative_to(HERE.parents[1])}")
    print("-" * 58)
    print(f"  rules documented                 {len(rows):>12}")
    print(f"  points in store                  {stored:>12,}")
    print(f"  usable for coverage              {usable:>12,}")
    undocumented = [r[0] for r in rows if r[3] == "-"]
    if undocumented:
        sys.exit(f"\n  FAILED - no threshold source for: {undocumented}")
    print("  every rule cites the decision that set its threshold")
    con.close()


if __name__ == "__main__":
    main()
